# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
tasks:
  - before: npm i -g pnpm
    init: pnpm install
    command: |
      export HMR_HOST=`gp url 3000`
      WEBHOOK_ENDPOINT_SIGN_UP=$WEBHOOK_ENDPOINT_SIGN_UP pnpm dev

ports:
  - port: 3000
    onOpen: ignore

github:
  prebuilds:
    addBadge: true
    branches: true

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - svelte.svelte-vscode
    - yzhang.markdown-all-in-one
