# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
image: gitpod/workspace-postgres

tasks:
  - before: npm i -g pnpm
    init: pnpm install
    command: |
      export HMR_HOST=`gp url 3000`
      pnpm dev

ports:
  - port: 3000
    onOpen: ignore
  - port: 5432
    onOpen: ignore

github:
  prebuilds:
    addBadge: true
    branches: true

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - svelte.svelte-vscode
    - yzhang.markdown-all-in-one
