// See https://developer.paddle.com/reference/ZG9jOjI1MzU0MDIy-supported-countries
// prettier-ignore
export const countries: {
  [isoCode: string]: {
    iso: string;
    name: string;
    postalCodeLabel?: string;
  }
} = {
  AD: { iso: "AD", name: "Andorra" },
  AE: { iso: "AE", name: "United Arab Emirates" },
  AF: { iso: "AF", name: "Afghanistan" },
  AG: { iso: "AG", name: "Antigua and Barbuda" },
  AI: { iso: "AI", name: "Anguilla" },
  AL: { iso: "AL", name: "Albania" },
  AM: { iso: "AM", name: "Armenia" },
  AN: { iso: "AN", name: "Netherlands Antilles" },
  AO: { iso: "AO", name: "Angola" },
  AR: { iso: "AR", name: "Argentina" },
  AS: { iso: "AS", name: "American Samoa" },
  AT: { iso: "AT", name: "Austria" },
  AU: { iso: "AU", name: "Australia", postalCodeLabel: "Postcode" },
  AW: { iso: "AW", name: "Aruba" },
  AZ: { iso: "AZ", name: "Azerbaijan" },
  BA: { iso: "BA", name: "Bosnia and Herzegovina" },
  BB: { iso: "BB", name: "Barbados" },
  BD: { iso: "BD", name: "Bangladesh" },
  BE: { iso: "BE", name: "Belgium" },
  BF: { iso: "BF", name: "Burkina Faso" },
  BG: { iso: "BG", name: "Bulgaria" },
  BH: { iso: "BH", name: "Bahrain" },
  BI: { iso: "BI", name: "Burundi" },
  BJ: { iso: "BJ", name: "Benin" },
  BM: { iso: "BM", name: "Bermuda" },
  BN: { iso: "BN", name: "Brunei Darussalam" },
  BO: { iso: "BO", name: "Bolivia" },
  BR: { iso: "BR", name: "Brazil" },
  BS: { iso: "BS", name: "Bahamas" },
  BT: { iso: "BT", name: "Bhutan" },
  BV: { iso: "BV", name: "Bouvet Island" },
  BW: { iso: "BW", name: "Botswana" },
  BY: { iso: "BY", name: "Belarus" },
  BZ: { iso: "BZ", name: "Belize" },
  CA: { iso: "CA", name: "Canada", postalCodeLabel: "Postal Code" },
  CC: { iso: "CC", name: "Cocos Islands" },
  CF: { iso: "CF", name: "Central African Republic" },
  CG: { iso: "CG", name: "Congo" },
  CH: { iso: "CH", name: "Switzerland" },
  CI: { iso: "CI", name: "Cote D’Ivoire" },
  CK: { iso: "CK", name: "Cook Islands" },
  CL: { iso: "CL", name: "Chile" },
  CM: { iso: "CM", name: "Cameroon" },
  CN: { iso: "CN", name: "China" },
  CO: { iso: "CO", name: "Colombia" },
  CR: { iso: "CR", name: "Costa Rica" },
  CU: { iso: "CU", name: "Cuba" },
  CV: { iso: "CV", name: "Cape Verde" },
  CW: { iso: "CW", name: "Curaçao" },
  CX: { iso: "CX", name: "Christmas Island" },
  CY: { iso: "CY", name: "Cyprus" },
  CZ: { iso: "CZ", name: "Czech Republic" },
  DE: { iso: "DE", name: "Germany", postalCodeLabel: "Postal / ZIP Code" },
  DJ: { iso: "DJ", name: "Djibouti" },
  DK: { iso: "DK", name: "Denmark" },
  DM: { iso: "DM", name: "Dominica" },
  DO: { iso: "DO", name: "Dominican Republic" },
  DZ: { iso: "DZ", name: "Algeria" },
  EC: { iso: "EC", name: "Ecuador" },
  EE: { iso: "EE", name: "Estonia" },
  EG: { iso: "EG", name: "Egypt" },
  EH: { iso: "EH", name: "Western Sahara" },
  ER: { iso: "ER", name: "Eritrea" },
  ES: { iso: "ES", name: "Spain", postalCodeLabel: "Postal / ZIP Code" },
  ET: { iso: "ET", name: "Ethiopia" },
  FI: { iso: "FI", name: "Finland" },
  FJ: { iso: "FJ", name: "Fiji" },
  FK: { iso: "FK", name: "Falkland Islands" },
  FM: { iso: "FM", name: "Micronesia" },
  FO: { iso: "FO", name: "Faroe Islands" },
  FR: { iso: "FR", name: "France", postalCodeLabel: "Postal / ZIP Code" },
  GA: { iso: "GA", name: "Gabon" },
  GB: { iso: "GB", name: "United Kingdom", postalCodeLabel: "Postcode" },
  GD: { iso: "GD", name: "Grenada" },
  GE: { iso: "GE", name: "Georgia" },
  GF: { iso: "GF", name: "French Guiana" },
  GG: { iso: "GG", name: "Guernsey" },
  GH: { iso: "GH", name: "Ghana" },
  GI: { iso: "GI", name: "Gibraltar" },
  GL: { iso: "GL", name: "Greenland" },
  GM: { iso: "GM", name: "Gambia" },
  GN: { iso: "GN", name: "Guinea" },
  GP: { iso: "GP", name: "Guadeloupe" },
  GQ: { iso: "GQ", name: "Equatorial Guinea" },
  GR: { iso: "GR", name: "Greece" },
  GS: { iso: "GS", name: "S. Georgia/ Sandwich Islands" },
  GT: { iso: "GT", name: "Guatemala" },
  GU: { iso: "GU", name: "Guam" },
  GW: { iso: "GW", name: "Guinea-Bissau" },
  GY: { iso: "GY", name: "Guyana" },
  HK: { iso: "HK", name: "Hong Kong" },
  HN: { iso: "HN", name: "Honduras" },
  HR: { iso: "HR", name: "Croatia" },
  HT: { iso: "HT", name: "Haiti" },
  HU: { iso: "HU", name: "Hungary" },
  ID: { iso: "ID", name: "Indonesia" },
  IE: { iso: "IE", name: "Ireland" },
  IL: { iso: "IL", name: "Israel" },
  IN: { iso: "IN", name: "India", postalCodeLabel: "Postcode" },
  IO: { iso: "IO", name: "Brit. Indian Ocean" },
  IQ: { iso: "IQ", name: "Iraq" },
  IR: { iso: "IR", name: "Iran" },
  IS: { iso: "IS", name: "Iceland" },
  IT: { iso: "IT", name: "Italy", postalCodeLabel: "Postal / ZIP Code" },
  JE: { iso: "JE", name: "Jersey" },
  JM: { iso: "JM", name: "Jamaica" },
  JO: { iso: "JO", name: "Jordan" },
  JP: { iso: "JP", name: "Japan" },
  KE: { iso: "KE", name: "Kenya" },
  KG: { iso: "KG", name: "Kyrgyzstan" },
  KH: { iso: "KH", name: "Cambodia" },
  KI: { iso: "KI", name: "Kiribati" },
  KM: { iso: "KM", name: "Comoros" },
  KN: { iso: "KN", name: "Saint Kitts and Nevis" },
  KP: { iso: "KP", name: "North Korea" },
  KR: { iso: "KR", name: "South Korea" },
  KW: { iso: "KW", name: "Kuwait" },
  KY: { iso: "KY", name: "Cayman Islands" },
  KZ: { iso: "KZ", name: "Kazakhstan" },
  LA: { iso: "LA", name: "Lao People’s DR" },
  LB: { iso: "LB", name: "Lebanon" },
  LC: { iso: "LC", name: "Saint Lucia" },
  LI: { iso: "LI", name: "Liechtenstein" },
  LK: { iso: "LK", name: "Sri Lanka" },
  LR: { iso: "LR", name: "Liberia" },
  LS: { iso: "LS", name: "Lesotho" },
  LT: { iso: "LT", name: "Lithuania" },
  LU: { iso: "LU", name: "Luxembourg" },
  LV: { iso: "LV", name: "Latvia" },
  LY: { iso: "LY", name: "Libyan Arab Jamahiriya" },
  MA: { iso: "MA", name: "Morocco" },
  MC: { iso: "MC", name: "Monaco" },
  MD: { iso: "MD", name: "Moldova" },
  ME: { iso: "ME", name: "Montenegro" },
  MG: { iso: "MG", name: "Madagascar" },
  MH: { iso: "MH", name: "Marshall Islands" },
  MK: { iso: "MK", name: "Macedonia" },
  ML: { iso: "ML", name: "Mali" },
  MM: { iso: "MM", name: "Myanmar" },
  MN: { iso: "MN", name: "Mongolia" },
  MO: { iso: "MO", name: "Macao" },
  MP: { iso: "MP", name: "Northern Mariana Islands" },
  MQ: { iso: "MQ", name: "Martinique" },
  MR: { iso: "MR", name: "Mauritania" },
  MS: { iso: "MS", name: "Montserrat" },
  MT: { iso: "MT", name: "Malta" },
  MU: { iso: "MU", name: "Mauritius" },
  MV: { iso: "MV", name: "Maldives" },
  MW: { iso: "MW", name: "Malawi" },
  MX: { iso: "MX", name: "Mexico" },
  MY: { iso: "MY", name: "Malaysia" },
  MZ: { iso: "MZ", name: "Mozambique" },
  NA: { iso: "NA", name: "Namibia" },
  NC: { iso: "NC", name: "New Caledonia" },
  NE: { iso: "NE", name: "Niger" },
  NF: { iso: "NF", name: "Norfolk Island" },
  NG: { iso: "NG", name: "Nigeria" },
  NI: { iso: "NI", name: "Nicaragua" },
  NL: { iso: "NL", name: "Netherlands", postalCodeLabel: "Postal / ZIP Code" },
  NO: { iso: "NO", name: "Norway" },
  NP: { iso: "NP", name: "Nepal" },
  NR: { iso: "NR", name: "Nauru" },
  NU: { iso: "NU", name: "Niue" },
  NZ: { iso: "NZ", name: "New Zealand" },
  OM: { iso: "OM", name: "Oman" },
  PA: { iso: "PA", name: "Panama" },
  PE: { iso: "PE", name: "Peru" },
  PF: { iso: "PF", name: "French Polynesia" },
  PG: { iso: "PG", name: "Papua New Guinea" },
  PH: { iso: "PH", name: "Philippines" },
  PK: { iso: "PK", name: "Pakistan" },
  PL: { iso: "PL", name: "Poland" },
  PM: { iso: "PM", name: "Saint Pierre and Miquelon" },
  PN: { iso: "PN", name: "Pitcairn" },
  PR: { iso: "PR", name: "Puerto Rico" },
  PS: { iso: "PS", name: "Palestinian Territory" },
  PT: { iso: "PT", name: "Portugal" },
  PW: { iso: "PW", name: "Palau" },
  PY: { iso: "PY", name: "Paraguay" },
  QA: { iso: "QA", name: "Qatar" },
  RE: { iso: "RE", name: "Reunion" },
  RO: { iso: "RO", name: "Romania" },
  RS: { iso: "RS", name: "Serbia" },
  RU: { iso: "RU", name: "Russian Federation" },
  RW: { iso: "RW", name: "Rwanda" },
  SA: { iso: "SA", name: "Saudi Arabia" },
  SB: { iso: "SB", name: "Solomon Islands" },
  SC: { iso: "SC", name: "Seychelles" },
  SD: { iso: "SD", name: "Sudan" },
  SE: { iso: "SE", name: "Sweden" },
  SG: { iso: "SG", name: "Singapore" },
  SH: { iso: "SH", name: "Saint Helena" },
  SI: { iso: "SI", name: "Slovenia" },
  SJ: { iso: "SJ", name: "Svalbard and Jan Mayen" },
  SK: { iso: "SK", name: "Slovakia" },
  SL: { iso: "SL", name: "Sierra Leone" },
  SM: { iso: "SM", name: "San Marino" },
  SN: { iso: "SN", name: "Senegal" },
  SO: { iso: "SO", name: "Somalia" },
  SR: { iso: "SR", name: "Suriname" },
  ST: { iso: "ST", name: "Sao Tome and Principe" },
  SV: { iso: "SV", name: "El Salvador" },
  SY: { iso: "SY", name: "Syrian Arab Republic" },
  SZ: { iso: "SZ", name: "Swaziland" },
  TC: { iso: "TC", name: "Turks and Caicos Islands" },
  TD: { iso: "TD", name: "Chad" },
  TG: { iso: "TG", name: "Togo" },
  TH: { iso: "TH", name: "Thailand" },
  TJ: { iso: "TJ", name: "Tajikistan" },
  TK: { iso: "TK", name: "Tokelau" },
  TL: { iso: "TL", name: "Timor-Leste" },
  TM: { iso: "TM", name: "Turkmenistan" },
  TN: { iso: "TN", name: "Tunisia" },
  TO: { iso: "TO", name: "Tonga" },
  TR: { iso: "TR", name: "Turkey" },
  TT: { iso: "TT", name: "Trinidad and Tobago" },
  TV: { iso: "TV", name: "Tuvalu" },
  TW: { iso: "TW", name: "Taiwan" },
  TZ: { iso: "TZ", name: "Tanzania" },
  UA: { iso: "UA", name: "Ukraine" },
  UG: { iso: "UG", name: "Uganda" },
  UM: { iso: "UM", name: "United States (M.O.I.)" },
  US: { iso: "US", name: "United States", postalCodeLabel: "ZIP Code" },
  UY: { iso: "UY", name: "Uruguay" },
  UZ: { iso: "UZ", name: "Uzbekistan" },
  VA: { iso: "VA", name: "Holy See/ Vatican City" },
  VC: { iso: "VC", name: "Saint Vincent/ Grenadines" },
  VE: { iso: "VE", name: "Venezuela" },
  VG: { iso: "VG", name: "British Virgin Islands" },
  VI: { iso: "VI", name: "U.S. Virgin Islands" },
  VN: { iso: "VN", name: "Vietnam" },
  VU: { iso: "VU", name: "Vanuatu" },
  WF: { iso: "WF", name: "Wallis and Futuna" },
  WS: { iso: "WS", name: "Samoa" },
  YE: { iso: "YE", name: "Yemen" },
  YT: { iso: "YT", name: "Mayotte" },
  ZA: { iso: "ZA", name: "South Africa" },
  ZM: { iso: "ZM", name: "Zambia" },
  ZW: { iso: "ZW", name: "Zimbabwe" },
};
